---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: dex
  description: Sistema responsavel por autenticar usuarios no cluster
spec:
  owner: kubernetes-team

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dex-authentication
  description: Sistema de autenticacao dos clusters
  annotations:
    backstage.io/kubernetes-label-selector: app.kubernetes.io/name=dex-k8s-authenticator
    backstage.io/kubernetes-namespace: dex
    backstage.io/kubernetes-cluster: eks-robinson
  links:
    - url: https://dexidp.io/docs/
      title: Documentação Dex
      icon: docs
spec:
  type: service
  lifecycle: development
  owner: kubernetes-team
  system: dex
  providesApis: [dex-api]
  dependsOn:
    - component:default/dex-core
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dex-core
  description: Sistema core do Dex
  annotations:
    backstage.io/kubernetes-label-selector: app.kubernetes.io/name=dex
    backstage.io/kubernetes-namespace: dex
    backstage.io/kubernetes-cluster: eks-robinson
  links:
    - url: https://dexidp.io/docs/
      title: Documentação Dex
      icon: docs
spec:
  type: service
  lifecycle: development
  owner: kubernetes-team
  system: dex
  providesApis: [dex-api]

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: dex-api
  description: api rest dex
spec:
  type: openapi
  lifecycle: development
  owner: kubernetes-team
  system: dex
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Dex API
      license:
        name: MIT
    servers:
      - url: http://dex.net/v1
    paths:
      /artists:
        get:
          summary: List all auth
