---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: Kubernetes
  description: Time responsavel pelo gerenciamento dos clusters k8s
spec:
  owner: kubernetes-team
  domain: kubernetes

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dex-authentication
  description: Sistema de autenticacao dos clusters
  annotations:
    backstage.io/kubernetes-label-selector: app=meu-web-server-nginx
    backstage.io/kubernetes-namespace: meu-web-server
    backstage.io/kubernetes-cluster: eks-robinson
spec:
  type: service
  lifecycle: development
  owner: kubernetes-team

